import { Food } from "./app/shared/models/Food";
export const sample_foods: Food[]=[
    {
        id:1,
        name:'Chiken Soup',
        price:11,
        cookTime:'12:40',
        favorite:false,
        origins:['Chine', 'Asia'],
        starts:3.0,
        imageUrl:'assets/images/soupe-chine.jpg',
        tags:['SlowFood', 'Soup'],
    },
    {
        id:4,
        name:'Chiken Soup',
        price:11,
        cookTime:'12:40',
        favorite:false,
        origins:['Algeria', 'Asia'],
        starts:3.0,
        imageUrl:'assets/images/soup.jpg',
        tags:['SlowFood', 'Soup'],
    },
    {
        id:2,
        name:'tagine ',
        price:11,
        cookTime:'12:40',
        favorite:false,
        origins:['Morocco', 'North Africa'],
        starts:3.0,
        imageUrl:'assets/images/tagine.jpg',
        tags:['SlowFood', 'heavy Food'],
    },
    {
        id:3,
        name:'Couscous',
        price:11,
        cookTime:'10:40',
        favorite:true,
        origins:['Morocco', 'Africa'],
        starts:3.0,
        imageUrl:'assets/images/couscous.jpeg',
        tags:['SlowFood', 'Heavy Foods'],
    },
    {
        id:6,
        name:'Couscous',
        price:11,
        cookTime:'10:40',
        favorite:true,
        origins:['Morocco', 'Africa'],
        starts:3.0,
        imageUrl:'assets/images/couscous-viande.jpg',
        tags:['SlowFood', 'Heavy Foods'],
    },
    {
        id:6,
        name:'Tagine',
        price:11,
        cookTime:'10:40',
        favorite:true,
        origins:['Morocco', 'Africa'],
        starts:3.0,
        imageUrl:'assets/images/tagine2.jpg',
        tags:['SlowFood', 'Heavy Foods'],
    },

]